CREATE DATABASE IF NOT EXISTS kubo_db;
USE kubo_db;

CREATE TABLE Worktickets (
    WTID INT AUTO_INCREMENT NOT NULL,
    TenantID INT(6) NOT NULL,
    Subject VARCHAR(255),
    Message VARCHAR(5000),
    Status VARCHAR(255),
    Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (WTID)
);

CREATE TABLE Landlords (
    LLID INT AUTO_INCREMENT NOT NULL,
    UserName VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Landlord BOOLEAN(1) DEFAULT 1 NOT NULL,
    PRIMARY KEY (LLID)
);

CREATE TABLE Tenants (
    TenantID INT AUTO_INCREMENT NOT NULL,
    UserName VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Landlord BOOLEAN(1) DEFAULT 0 NOT NULL,
    PRIMARY KEY (TenantID)
);

CREATE TABLE Properties (
    PropID INT AUTO_INCREMENT NOT NULL,
    PropName VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    State VARCHAR(255) NOT NULL,
    Zipcode INT(5) NOT NULL,
    PRIMARY KEY (PropID)
);

CREATE TABLE Notifications (
    NoticeID INT AUTO_INCREMENT NOT NULL,
    PropID INT(6) NOT NULL,
    Message VARCHAR(5000) NOT NULL,
    Expiration VARCHAR(10) NOT NULL,
    Posted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NoticeID)
);

CREATE TABLE UnitID (
    UnitID INT AUTO_INCREMENT NOT NULL,
    unitName VARCHAR(25) NOT NULL,
    PropID INT(6) NOT NULL,
    PRIMARY KEY (UnitID)
);

CREATE TABLE TenantID_UnitID (
    ID INT AUTO_INCREMENT NOT NULL,
    UnitID INT(6),
    TenantID INT(6),
    PRIMARY KEY (ID)
);

CREATE TABLE LLID_PropID (
    ID INT AUTO_INCREMENT NOT NULL,
    LLID INT(6) NOT NULL,
    PropID INT(6) NOT NULL,
    PRIMARY KEY (ID)
);